@include('includes.head')
@include('includes.h1')
@include('includes.loading')
@include('includes.header')
@include('includes.menu')
@yield('content')
@include('includes.chat')
@include('includes.footer')
